# Generated by Django 4.0.1 on 2022-02-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_details',
            field=models.CharField(default='details', max_length=500),
        ),
    ]
