# Generated by Django 4.0.1 on 2022-03-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_age_profile_degree_profile_disease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Disease',
            new_name='disease',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='labaddress',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='labname',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
