# Generated by Django 3.1.7 on 2022-02-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lab_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('report_img', models.ImageField(default='default.png', upload_to='report_img/')),
                ('segment_img', models.ImageField(default='default.png', upload_to='report_img/')),
                ('report_summary', models.CharField(max_length=500)),
                ('medicines', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(default='others', on_delete=django.db.models.deletion.CASCADE, to='segmi.doctor')),
                ('patient', models.ForeignKey(default='others', on_delete=django.db.models.deletion.CASCADE, to='segmi.patient')),
            ],
        ),
    ]
