# Generated by Django 4.0.1 on 2022-02-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segmi', '0002_auto_20220204_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_report',
            name='lab',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='segmi.lab'),
        ),
    ]
