# Generated by Django 4.0.1 on 2022-03-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_age_profile_age_rename_degree_profile_degree_and_more'),
        ('segmi', '0003_lab_report_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_report',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Doctor', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='lab_report',
            name='lab',
            field=models.ForeignKey(limit_choices_to={'category': 'Lab_user'}, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='lab_report',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Patient', to='users.profile'),
        ),
    ]
