# Generated by Django 4.0.3 on 2022-04-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmi', '0005_alter_lab_report_doctor_alter_lab_report_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=500)),
                ('doctor', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
